apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wander
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  hostPath:
    path: /data/db
    type: DirectoryOrCreate