apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wander
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongo-service/wanderlust
  REDIS_URL: redis://redis-service:6379
  JWT_SECRET: 70dd8b38486eee723ce2505f6db06f1ee503fde5eb06fc04687191a0ed665f3f98776902d2c89f6b993b1c579a87fedaf584c693a106f7cbf16e8b4e67e9d6df
  FRONTEND_URL: http://frontend.wander.example.com
  VITE_API_PATH: http://backend.wander.example.com
  NODE_ENV: Development
  PORT: "5000"