name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: manish181623/wanderlust-ci-cd-fe
        
      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: manish181623/wanderlust-ci-cd-be

      - name: Run Trivy scan on Frontend Docker image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: manish181623/wanderlust-ci-cd-fe
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy scan on Backend Docker image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: manish181623/wanderlust-ci-cd-be
          format: 'table'
          severity: 'CRITICAL,HIGH'